import { prisma } from "../prisma/client";
import { CreatePreSessionInput } from "../validators/preSessions.validator";

export async function createPreSession(data: CreatePreSessionInput) {
  return prisma.preSession.create({
    data: {
      intention: data.intention,
      // timestamp is auto-generated by Prisma
    },
  });
}

export async function getPreSessions(limit: number, order: "asc" | "desc") {
  return prisma.preSession.findMany({
    take: limit,
    orderBy: { timestamp: order },
  });
}